repos:
  - repo: local
    hooks:
      - id: poe-format-check
        name: Poe Format Check
        entry: uv run poe format_check
        language: system
        pass_filenames: false
        always_run: true
      - id: poe-lint
        name: Poe Lint
        entry: uv run poe lint
        language: system
        pass_filenames: false
        always_run: true
      - id: poe-typecheck
        name: Poe Typecheck
        entry: uv run poe typecheck
        language: system
        pass_filenames: false
        always_run: true
      - id: poe-test
        name: Poe Test
        entry: uv run poe test
        language: system
        pass_filenames: false
        always_run: true
